### ISSUE TITLE
Please enter a short (15 lines) overview of all the new things for your project since your last FOSDEM and anything new to expect this year. This will be added to your stand on the overview website.

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/FOSDEM#12]

**Comment by diva-exchange** [comment]
I2P has built SSU2 etc. ... (please fill in details here).

Since the last FOSDEM (2020) DIVA.EXCHANGE has significantly increased the speed, stability and energy efficiency of the distributed storage layer (known as "divachain"). New research has been published in summer 2022 together with University of Applied Science, Lucerne (HSLU), about "How to de-anonymize I2P network participants". In Winter 2022/2023 a fully distributed, trustless, self-hosted, DNS registrar service for I2P gets developed by students of HSLU, based on I2P and divachain.

**Comment by Shoalsteed** [comment]
I2P has improved its onboarding and usability for the core Java distribution significantly thanks to JPackage. It also has produced new installers for Windows and Mac users.

I2P has also completed the  decade-long plan to upgrade all the cryptography from the original Java I2P implementation dating back to 2003.  "SSU2", a modern UDP protocol designed to the highest standards of security and blocking resistance has ben designed an implemented. 
It combines industry-standard encryption with the best features of UDP protocols WireGuard and QUIC, together with the censorship resistance features of I2P's TCP protocol "NTCP2". SSU2 may be one of the most secure transport protocols ever designed.
